site_name: Legal Study Platform
site_description: Documentation for the Legal Study Platform
site_author: Legal Study Team
repo_name: legal-study
repo_url: https://github.com/legal-study
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Development:
    - Development Environment: development/environment.md
    - Testing: development/testing.md
    - Contributing: development/contributing.md
  - Features:
    - API Documentation: features/api.md
    - Authentication: features/authentication.md
    - Database: features/database.md
  - Deployment:
    - GitHub Codespaces: deployment/codespaces.md
    - Docker: deployment/docker.md
    - CI/CD: deployment/ci-cd.md
  - Reference:
    - API Reference: reference/api.md
    - Configuration: reference/configuration.md
    - Troubleshooting: reference/troubleshooting.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/legal-study
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/legal-study
  version:
    provider: mike
