# Unit Testing Configuration

# Environment settings
environment:
  python_version: "3.9"
  use_venv: true
  dependencies:
    - pytest
    - pytest-cov
    - pytest-html
    - pytest-xdist
    - pytest-timeout
    - pytest-randomly
    - pytest-mock
    - pytest-asyncio
    - pytest-env
    - pytest-sugar
    - pytest-clarity
    - pytest-benchmark
    - pytest-profiling
    - pytest-custom-exit-code
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-selenium
    - pytest-vcr
    - pytest-watch
    - pytest-xprocess

# Execution settings
execution:
  parallel: true
  workers: auto
  timeout: 300
  retries: 3
  random_seed: 123

# Coverage settings
coverage:
  minimum_coverage: 80
  exclude_patterns:
    - "tests/*"
    - "docs/*"
    - "setup.py"
    - "*/__init__.py"
    - "*/migrations/*"
    - "*/static/*"
    - "*/templates/*"

# Test directories
test_directories:
  - tests/unit
  - tests/integration
  - tests/functional
  - tests/performance

# Test categories
test_categories:
  unit:
    pattern: "test_*.py"
    markers:
      - unit
      - fast
  integration:
    pattern: "test_*.py"
    markers:
      - integration
      - slow
  functional:
    pattern: "test_*.py"
    markers:
      - functional
      - e2e
  performance:
    pattern: "test_*.py"
    markers:
      - performance
      - benchmark

# Reporting settings
reporting:
  directory: "reports"
  formats:
    - html
    - xml
    - json
  html:
    self_contained: true
    template: "templates/report.html"
  junit:
    output: "reports/junit.xml"
  coverage:
    output: "reports/coverage"
    formats:
      - html
      - xml
      - json

# Documentation settings
documentation:
  directory: "reports/documentation"
  formats:
    - markdown
    - html
  sections:
    - test_results
    - coverage_report
    - issues
    - resolutions
    - environment
    - dependencies

# Logging settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  directory: "logs"
  file: "unit_tests_{timestamp}.log"

# Error handling
error_handling:
  retry_failed: true
  max_retries: 3
  retry_delay: 5
  fail_fast: false
  continue_on_error: true

# Performance settings
performance:
  timeout: 300
  memory_limit: "2GB"
  cpu_limit: 80

# Security settings
security:
  scan_dependencies: true
  check_vulnerabilities: true
  validate_requirements: true
