version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DB_HOST=codespaces-mysql
      - DB_PORT=3306
      - REDIS_HOST=codespaces-redis
      - REDIS_PORT=6379
    depends_on:
      - codespaces-mysql
      - codespaces-redis

  codespaces-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: legal_study
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  codespaces-redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
