aws:
  region: us-east-1
  services:
  - ec2
  - rds
  - s3
  - cloudwatch
docker:
  compose_version: '2.0'
  services:
  - api
  - frontend
  - database
  - cache
environment:
  docker_version: '20.10'
  node_version: '18'
  python_version: '3.10'
github:
  branch_protection: true
  required_checks:
  - test
  - lint
  - security
