global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'platform_api'
    static_configs:
      - targets: ['platform_api:8000']
    metrics_path: '/metrics'

  - job_name: 'ai_service'
    static_configs:
      - targets: ['ai_service:8001']
    metrics_path: '/metrics'

  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:8002']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
