version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .codespaces/Dockerfile
    volumes:
      - .:/var/www
      - ./.codespaces/data:/var/www/.codespaces/data
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=codespaces
      - DB_USERNAME=root
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    networks:
      - codespaces

  mysql:
    image: mysql:8.0
    container_name: codespaces-mysql
    environment:
      MYSQL_DATABASE: codespaces
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codespaces

  redis:
    image: redis:alpine
    container_name: codespaces-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codespaces

networks:
  codespaces:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
